<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <RootNamespace>Arma3ServerTools.MonitoringHost</RootNamespace>
    <AssemblyName>Arma3ServerTools.MonitoringHost</AssemblyName>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>..\Arma3ServerTools.App.WinForms\Assets\1_arma3server_x64.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Arma3ServerTools.Application\Arma3ServerTools.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\sql\a3st_statistics.sql" Link="sql\a3st_statistics.sql">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\sql\a3st_players.sql" Link="sql\a3st_players.sql">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
