/** Default values for all config sections — matching C# defaults */
export const DEFAULTS: Record<string, Record<string, unknown>> = {
  server: {
    configName: "新服务器",
    serverDir: "C:\\arma3",
    executable: "arma3server_x64.exe",
    x64: true,
    modDir: "",
  },
  startup: {
    parameters: "-world=empty -skipIntro -noPause -enableHT",
    cpuCount: 0,
    exThreads: 0,
    maxMem: 0,
    limitFps: 60,
    viewDistance: 1600,
    terrainGrid: 25,
    enableHT: true,
    hugepages: false,
    loadMissionToMemory: true,
    disableServerThread: false,
    logObjectNotFound: false,
    skipDescriptionParsing: false,
    ignoreMissionLoadErrors: true,
    queueSizeLogG: 1000000,
    uploadMbps: 100,
    port: 2302,
    autoInit: false,
    restartOnCrash: true,
    startupDelay: 0,
    startArgs: "",
  },
  basic: {
    hostname: "Arma3 Server",
    password: "",
    passwordAdmin: "",
    maxPlayers: 64,
    port: 2302,
    persistent: true,
    skipLobby: false,
    drawingInMap: true,
    statisticsEnabled: 0,
    forceRotorLibSimulation: 0,
    battlEye: true,
    verifySignatures: 2,
    kickDuplicate: true,
    allowedFilePatching: 0,
    filePatchingExceptions: "",
    motd: "Welcome to Arma3 Server",
    motdInterval: 30,
    disableVoN: false,
    vonCodecQuality: 8,
    vonCodec: "SPEEX",
    enableHeadlessClient: false,
    headlessClients: "",
    localClient: "127.0.0.1",
    voteThreshold: 2,
    votingTimeout: 30,
    roleTimeout: 0,
    briefingTimeout: 0,
    debriefingTimeout: 0,
    lobbyIdleTimeout: 0,
    voteMissionPlayers: 1,
    pidFile: "",
    rankingFile: "",
    logFile: "server_console.log",
    timeStampFormat: 1,
    callExtReportLimit: 10000,
    noLogs: false,
    netLog: false,
    serverCfgArgs: "",
    basicCfgArgs: "",
    profileArgs: "",
    serverCommandPassword: "",
    admins: "",
    doubleIdDetected: "",
    onUserConnected: "",
    onUserDisconnected: "",
    onUserKicked: "",
    regularCheck: "",
    onHackedData: "",
    onDifferentData: "",
    onUnsignedData: "",
    allowedLoadFile: "",
    allowedPreprocess: "",
    allowedHtmlLoad: "",
    allowedHtmlUri: "",
    maxCreateVehicleCount: 0,
    maxCreateVehicleSeconds: 0,
    maxSetPosCount: 0,
    maxSetPosSeconds: 0,
    disconnectTimeout: 90,
    maxDesync: 150,
    maxPing: 200,
    maxPacketLoss: 0,
    upnp: false,
    loopback: false,
    bandwidthAlg: false,
    maxMsgSend: 128,
    maxSizeGuaranteed: 512,
    maxSizeNonguaranteed: 256,
    minBandwidth: 131072,
    maxBandwidth: 1048576,
    maxPacketSize: 1400,
    maxCustomFileSize: 0,
    minErrorToSend: 0.001,
    minErrorToSendNear: 0.01,
    // Difficulty
    groupIndicators: "2",
    friendlyTags: "2",
    enemyTags: "0",
    detectedMines: "2",
    commands: "2",
    waypoints: "2",
    weaponInfo: "2",
    stanceIndicator: "2",
    tacticalPing: "2",
    staminaBar: true,
    weaponCrosshair: true,
    visionAid: false,
    cameraShake: true,
    scoreTable: true,
    deathMessages: true,
    vonId: true,
    mapContent: true,
    mapContentFriendly: true,
    mapContentEnemy: false,
    mapContentMines: false,
    reducedDamage: false,
    autoReport: false,
    multipleSaves: true,
    skillAi: 0.5,
    precisionAi: 0.5,
    thirdPerson: 1,
  },
  battleye: {
    rconPort: 2302,
    rconPassword: "",
    rconHost: "127.0.0.1",
    beMaxPing: 200,
    bePath: "BattlEye",
  },
  mods: {
    enabledIds: [],
    serverModIds: [],
    clientModIds: [],
    hcModIds: [],
    autoCopyBikey: true,
    modPaths: [],
  },
  scheduler: {
    restartCron: "0 4 * * *",
    monitoringCron: "*/5 * * * *",
  },
  monitoring: {},
};

/** Apply defaults to a config object, filling in missing fields */
export function applyDefaults(config: Record<string, unknown>): Record<string, unknown> {
  const result = { ...config };
  for (const [section, defaults] of Object.entries(DEFAULTS)) {
    const current = (result[section] ?? {}) as Record<string, unknown>;
    result[section] = { ...defaults, ...current };
  }
  return result;
}
