/** 界面统一用语（用户侧词汇，与后端 action 名解耦） */
export const UI_COPY = {
  saveConfig: "保存到配置包",
  saveShort: "保存",
  writeGameCfg: "写入游戏配置",
  writeCfgAfterOp: "完成后写入游戏配置",
  preflight: "开服检查",
  syncWritten: "已写入游戏配置",
  syncStale: "需写入游戏配置",
  syncPending: "未写入游戏配置",
  dirtySuffix: "未保存",
  connectionTitle: "主机连接",
  connectionEmpty: "尚未添加主机",
  connectionEmptyHint: "添加本机或被控服务地址后即可管理 Arma 3 服务器",
  firstServerWizard: "首服向导",
  firstServerEmptyHint: "尚无服务器配置，可使用首服向导从零创建",
  addHost: "添加主机...",
  addHostDialog: "添加主机",
  modsImport: "导入模组",
  modsImportHint: "添加本地目录、扫描路径、下载 Workshop 模组，或从 HTML / 剪贴板导入 ID",
  modsSelected: "已选",
  modsSelectedHint: "是否加载该模组（写入 server.cfg 的 mods 列表）",
  modsServerMod: "服模",
  modsServerModHint: "作为服务器模组（-serverMod）加载",
  modsClientMod: "客模",
  modsClientModHint: "作为客户端模组（-mod）加载，玩家需同步订阅",
  modsHcMod: "HC",
  modsHcModHint: "作为无头客户端（HC）模组加载",
  modsSignature: "签名",
  modsSignatureHint: "Bikey 签名状态：验证通过 / 未复制 / 无密钥 / 未签名",
} as const;
