; Auto-generated by build-release.ps1 鈥?do not commit.
#define MyAppVersion "1.6.0"
#define MyAppVersionInfo "1.6.0.0"
#define MyAppCopyright "Copyright (C) 2026 ViVi141. Based on original work copyright 2022 destiny studio (Blue, 七龙)."
#define PublishDir "C:\Users\74738\Desktop\arma3-server-tool\artifacts\_publish"
#define MyBuildStamp "20260611-220801"
