#Requires -Version 5.1

param(
    [ValidateSet("Release", "Debug")]
    [string] $Configuration = "Release",

    [bool] $SelfContained = $true,

    [string] $Version = "",

    [switch] $SkipInstaller,

    [switch] $Zip,

    [switch] $InstallInnoSetup
)

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $PSScriptRoot
Set-Location $Root

function Read-DirectoryBuildProp {
    param(
        [string] $PropertyName
    )

    $propsPath = Join-Path $Root "Directory.Build.props"
    if (-not (Test-Path $propsPath)) {
        return $null
    }

    [xml]$doc = Get-Content -Path $propsPath -Encoding UTF8
    foreach ($group in $doc.Project.PropertyGroup) {
        $value = $group.$PropertyName
        if (-not [string]::IsNullOrWhiteSpace($value)) {
            return [string]$value
        }
    }

    return $null
}

function ConvertTo-FourPartVersion {
    param(
        [string] $Version
    )

    $parts = $Version.Split(".")
    while ($parts.Count -lt 4) {
        $parts += "0"
    }

    return ($parts[0..3] -join ".")
}

function Resolve-ReleaseVersion {
    param(
        [string] $RequestedVersion
    )

    if (-not [string]::IsNullOrWhiteSpace($RequestedVersion)) {
        return $RequestedVersion.Trim()
    }

    $propsVersion = Read-DirectoryBuildProp -PropertyName "Version"
    if (-not [string]::IsNullOrWhiteSpace($propsVersion)) {
        return $propsVersion
    }

    return "1.0.0"
}

$Version = Resolve-ReleaseVersion -RequestedVersion $Version
$VersionInfo = ConvertTo-FourPartVersion -Version $Version
$AppPublisher = Read-DirectoryBuildProp -PropertyName "Company"
if ([string]::IsNullOrWhiteSpace($AppPublisher)) {
    $AppPublisher = "ViVi141"
}

$AppCopyright = Read-DirectoryBuildProp -PropertyName "Copyright"
if ([string]::IsNullOrWhiteSpace($AppCopyright)) {
    $AppCopyright = "Copyright (C) 2026 ViVi141"
}

function Write-InnoBuildMetadata {
    param(
        [string] $Version,
        [string] $VersionInfo,
        [string] $Copyright,
        [string] $PublishDir,
        [string] $BuildStamp
    )

    $metadataPath = Join-Path $PSScriptRoot "_build-metadata.iss"
    $escapedCopyright = $Copyright.Replace('"', '""')
    $escapedPublishDir = $PublishDir.Replace('"', '""')
    $escapedBuildStamp = $BuildStamp.Replace('"', '""')
    $content = @"
; Auto-generated by build-release.ps1 — do not commit.
#define MyAppVersion "$Version"
#define MyAppVersionInfo "$VersionInfo"
#define MyAppCopyright "$escapedCopyright"
#define PublishDir "$escapedPublishDir"
#define MyBuildStamp "$escapedBuildStamp"
"@

    Set-Content -Path $metadataPath -Value $content -Encoding UTF8
    return $metadataPath
}

$BuildStamp = (Get-Date).ToString("yyyyMMdd-HHmmss")
$SetupFileName = "Arma3ServerTools-Setup-v$Version-$BuildStamp.exe"

function Get-InnoSetupCompiler {
    $candidates = @(
        $env:INNO_SETUP_PATH,
        (Join-Path $Root "tools\innosetup-6\ISCC.exe"),
        (Join-Path $env:LOCALAPPDATA "Programs\Inno Setup 6\ISCC.exe"),
        "${env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe",
        "$env:ProgramFiles\Inno Setup 6\ISCC.exe"
    )

    foreach ($candidate in $candidates) {
        if (-not [string]::IsNullOrWhiteSpace($candidate) -and (Test-Path $candidate)) {
            return (Resolve-Path $candidate).Path
        }
    }

    return $null
}

function Install-InnoSetupCompiler {
    $targetDir = Join-Path $Root "tools\innosetup-6"
    if (Test-Path (Join-Path $targetDir "ISCC.exe")) {
        return (Resolve-Path (Join-Path $targetDir "ISCC.exe")).Path
    }

    $winget = Get-Command winget -ErrorAction SilentlyContinue
    if ($winget) {
        Write-Host "Installing Inno Setup 6 via winget ..."
        & winget install --id JRSoftware.InnoSetup -e --accept-package-agreements --accept-source-agreements --silent
        $iscc = Get-InnoSetupCompiler
        if ($iscc) {
            return $iscc
        }
    }

    $installerPath = Join-Path $env:TEMP ("innosetup-" + [Guid]::NewGuid().ToString("N") + ".exe")
    $downloadUrl = "https://github.com/jrsoftware/issrc/releases/download/is-6_7_2/innosetup-6.7.2.exe"
    Write-Host "Downloading Inno Setup 6 from $downloadUrl ..."
    Invoke-WebRequest -Uri $downloadUrl -OutFile $installerPath

    if (-not (Test-Path $targetDir)) {
        New-Item -ItemType Directory -Path $targetDir | Out-Null
    }

    Write-Host "Installing Inno Setup 6 to $targetDir ..."
    $installArgs = @(
        "/VERYSILENT",
        "/SUPPRESSMSGBOXES",
        "/NORESTART",
        "/DIR=`"$targetDir`""
    )
    $process = Start-Process -FilePath $installerPath -ArgumentList $installArgs -Wait -PassThru
    Remove-Item -Force $installerPath -ErrorAction SilentlyContinue

    if ($process.ExitCode -ne 0) {
        throw "Inno Setup installer exited with code $($process.ExitCode)."
    }

    $iscc = Get-InnoSetupCompiler
    if (-not $iscc) {
        throw "Inno Setup was installed but ISCC.exe was not found."
    }

    return $iscc
}

function Resolve-InnoSetupCompiler {
    param(
        [switch] $AllowInstall
    )

    $iscc = Get-InnoSetupCompiler
    if ($iscc) {
        return $iscc
    }

    if ($AllowInstall) {
        return Install-InnoSetupCompiler
    }

    throw @"
Inno Setup 6 (ISCC.exe) was not found.

Install Inno Setup 6 and ensure ISCC.exe is on PATH, or set INNO_SETUP_PATH, or rerun with -InstallInnoSetup:

  powershell -ExecutionPolicy Bypass -File scripts/build-release.ps1 -InstallInnoSetup

Download: https://jrsoftware.org/isdl.php
"@
}

Write-Host "Building Arma3ServerTools v$Version ($Configuration)..."

dotnet restore Arma3ServerTools.sln
if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

dotnet build Arma3ServerTools.sln -c $Configuration --no-restore
if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

dotnet test Arma3ServerTools.sln -c $Configuration --no-build
if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

$PublishDir = Join-Path $Root "artifacts\_publish"
if (Test-Path $PublishDir) {
    Remove-Item -Recurse -Force $PublishDir
}

$PublishArgs = @(
    "publish",
    "src\Arma3ServerTools.App.WinForms\Arma3ServerTools.App.WinForms.csproj",
    "-c", $Configuration,
    "-o", $PublishDir
)

if ($SelfContained) {
    $PublishArgs += @("-r", "win-x64", "--self-contained", "true")
}
else {
    $PublishArgs += @("--self-contained", "false")
}

dotnet @PublishArgs
if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

function Publish-SatelliteHost {
    param(
        [Parameter(Mandatory = $true)]
        [string] $ProjectRelativePath,

        [Parameter(Mandatory = $true)]
        [string] $DestinationSubDirectory,

        [Parameter(Mandatory = $true)]
        [string] $ExpectedExeName
    )

    $destination = Join-Path $PublishDir $DestinationSubDirectory
    if (Test-Path $destination) {
        Remove-Item -Recurse -Force $destination
    }

    $satellitePublishArgs = @(
        "publish",
        $ProjectRelativePath,
        "-c", $Configuration,
        "-o", $destination,
        "--no-restore"
    )

    if ($SelfContained) {
        $satellitePublishArgs += @("-r", "win-x64", "--self-contained", "true")
    }
    else {
        $satellitePublishArgs += @("--self-contained", "false")
    }

    Write-Host "Publishing $ExpectedExeName to $destination ..."
    dotnet @satellitePublishArgs
    if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

    $expectedExePath = Join-Path $destination $ExpectedExeName
    if (-not (Test-Path $expectedExePath)) {
        throw "Expected satellite host was not published: $expectedExePath"
    }
}

Publish-SatelliteHost `
    -ProjectRelativePath "src\Arma3ServerTools.MonitoringHost\Arma3ServerTools.MonitoringHost.csproj" `
    -DestinationSubDirectory "monitoring" `
    -ExpectedExeName "Arma3ServerTools.MonitoringHost.exe"

Publish-SatelliteHost `
    -ProjectRelativePath "src\Arma3ServerTools.Agent.Host\Arma3ServerTools.Agent.Host.csproj" `
    -DestinationSubDirectory "agent" `
    -ExpectedExeName "Arma3ServerTools.Agent.Host.exe"

$SkillsSource = Join-Path $Root "skills"
if (Test-Path $SkillsSource) {
    $SkillsDest = Join-Path $PublishDir "skills"
    if (Test-Path $SkillsDest) {
        Remove-Item -Recurse -Force $SkillsDest
    }
    Copy-Item -Path $SkillsSource -Destination $SkillsDest -Recurse -Force
    $skillMdPath = Join-Path $SkillsDest "arma3-server-tools\SKILL.md"
    if (-not (Test-Path $skillMdPath)) {
        throw "OpenClaw skill file was not copied: $skillMdPath"
    }
    Write-Host "Bundled OpenClaw skill: $skillMdPath"
}
else {
    throw "Skills directory not found: $SkillsSource"
}

$guideTxtPath = Join-Path $PublishDir "docs\first-server-guide.txt"
if (-not (Test-Path $guideTxtPath)) {
    throw "First-server guide (txt) was not copied to publish output: $guideTxtPath"
}
Write-Host "Bundled first-server guide: $guideTxtPath"

$OpenClawScriptSource = Join-Path $Root "scripts\openclaw"
if (Test-Path $OpenClawScriptSource) {
    $ScriptsDest = Join-Path $PublishDir "scripts\openclaw"
    New-Item -ItemType Directory -Path (Split-Path $ScriptsDest -Parent) -Force | Out-Null
    if (Test-Path $ScriptsDest) {
        Remove-Item -Recurse -Force $ScriptsDest
    }
    Copy-Item -Path $OpenClawScriptSource -Destination $ScriptsDest -Recurse -Force
}

foreach ($legalFile in @("LICENSE", "NOTICE", "THIRD-PARTY-NOTICES.txt")) {
    $sourcePath = Join-Path $Root $legalFile
    if (Test-Path $sourcePath) {
        Copy-Item -Path $sourcePath -Destination (Join-Path $PublishDir $legalFile) -Force
    }
}

$MainExePath = Join-Path $PublishDir "Arma3ServerTools.exe"
$AgentExePath = Join-Path $PublishDir "agent\Arma3ServerTools.Agent.Host.exe"
$MonitoringExePath = Join-Path $PublishDir "monitoring\Arma3ServerTools.MonitoringHost.exe"
if (-not (Test-Path $MainExePath)) {
    throw "Main application was not published: $MainExePath"
}
if (-not (Test-Path $AgentExePath)) {
    throw "Agent host was not published: $AgentExePath"
}
if (-not (Test-Path $MonitoringExePath)) {
    throw "Monitoring host was not published: $MonitoringExePath"
}

$SetupPath = Join-Path $Root ("artifacts\" + $SetupFileName)
if (-not $SkipInstaller) {
    $iscc = Resolve-InnoSetupCompiler -AllowInstall:$InstallInnoSetup
    $issPath = Join-Path $PSScriptRoot "Arma3ServerTools.iss"
    Write-InnoBuildMetadata -Version $Version -VersionInfo $VersionInfo -Copyright $AppCopyright -PublishDir $PublishDir -BuildStamp $BuildStamp | Out-Null

    Write-Host ""
    Write-Host "Compiling installer with Inno Setup ..."
    & $iscc $issPath
    if ($LASTEXITCODE -ne 0) {
        exit $LASTEXITCODE
    }

    $expectedOutputBase = "Arma3ServerTools-Setup-$Version-$BuildStamp.exe"
    $expectedOutputPath = Join-Path $Root ("artifacts\" + $expectedOutputBase)
    if (-not (Test-Path $expectedOutputPath)) {
        throw "Installer build finished but output was not created: $expectedOutputPath"
    }

    $SetupFileName = $expectedOutputBase
    $SetupPath = $expectedOutputPath
}

$ZipPath = $null
if ($Zip) {
    $artifactName = "Arma3ServerTools-v$Version-$Configuration"
    if ($SelfContained) {
        $artifactName = $artifactName + "-win-x64"
    }

    $ZipPath = Join-Path $Root "artifacts\$artifactName.zip"
    if (Test-Path $ZipPath) {
        Remove-Item -Force $ZipPath
    }

    Compress-Archive -Path (Join-Path $PublishDir "*") -DestinationPath $ZipPath
}

Write-Host ""
Write-Host "Publish staging: $PublishDir"
Write-Host "  Main:       $MainExePath"
Write-Host "  Agent:      $AgentExePath"
Write-Host "  Monitoring: $MonitoringExePath"
$SkillMdPath = Join-Path $PublishDir "skills\arma3-server-tools\SKILL.md"
if (Test-Path $SkillMdPath) {
    Write-Host "  Skill:      $SkillMdPath"
}
if (Test-Path $SetupPath) {
    Write-Host "Setup installer: $SetupPath"
}
if ($ZipPath) {
    Write-Host "Portable zip:    $ZipPath"
}
Write-Host ""
Write-Host "To publish GitHub Release v${Version}:"
Write-Host "  1. Commit all changes"
Write-Host "  2. git tag -a v${Version} -m ""Arma3 Server Tools v${Version}"""
Write-Host "  3. git push origin v${Version}"
if (Test-Path $SetupPath) {
    Write-Host "  4. Upload artifacts\$SetupFileName to GitHub Releases"
}
