<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>Arma3ServerTools.Application.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.0.2">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\TestSupport\AutomatedTestWorkspace.cs" Link="TestSupport\AutomatedTestWorkspace.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\sql\destiny_statistics.sql" Link="sql\destiny_statistics.sql">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\sql\destiny_players.sql" Link="sql\destiny_players.sql">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Arma3ServerTools.Application\Arma3ServerTools.Application.csproj" />
    <ProjectReference Include="..\..\src\Arma3ServerTools.Core\Arma3ServerTools.Core.csproj" />
  </ItemGroup>

</Project>
